### ISSUE TITLE
Https support

### ISSUE THREAD

**Issue by BBS007** [WatchDogZZ/server#6]

**Comment by pcolomb** [comment]
https://letsencrypt.org/

**Comment by BBS007** [comment]
Using [Letsencrypt-express](https://www.npmjs.com/package/letsencrypt-express) module.

**Comment by begarco** [comment]
J'ai résolu le problème en ajoutant le certificateur qui fourni ton certificat à la liste des autorisations.

**Comment by BBS007** [comment]
Ouh ! Nickel !
